import { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * SpoonOS Cookbook Documentation Sidebar Configuration
 *
 * Organized following DeepWiki/LangChain pattern:
 * - Progressive learning path from basics to advanced
 * - Task-oriented how-to guides
 * - Comprehensive API reference
 * - Practical examples and troubleshooting
 */

const sidebars: SidebarsConfig = {
  // Main documentation sidebar with hierarchical structure
  tutorialSidebar: [
    {
      type: 'category',
      label: '🚀 Getting Started',
      collapsed: false,
      items: [
        'getting-started/installation',
        'getting-started/configuration',
        'getting-started/quick-start',
      ],
    },
    {
      type: 'category',
      label: '🧠 Core Concepts',
      collapsed: false,
      items: [
        'core-concepts/agents',
        'core-concepts/tools',
        'core-concepts/llm-providers',
        'core-concepts/mcp-protocol',
        'core-concepts/Short-term memory',
        'core-concepts/x402-payments',
        'core-concepts/long-term memory',
      ],
    },
    {
      type: 'category',
      label: '📊 Graph System',
      collapsed: false,
      link: {
        type: 'doc',
        id: 'graph-system/index',
      },
      items: [
        'graph-system/quick-start',
        'graph-system/core-concepts',
        'graph-system/building-graphs',
        'graph-system/advanced-features',
        'graph-system/integration',
        'graph-system/examples',
      ],
    },
    {
      type: 'category',
      label: '📖 How-To Guides',
      collapsed: false,
      items: [
        'how-to-guides/build-first-agent',
        'how-to-guides/add-custom-tools',
        'how-to-guides/vibe-coding',
        'how-to-guides/x402-payments',
      ],
    },
    // {
    //   type: 'category',
    //   label: '💻 CLI Usage',
    //   collapsed: false,
    //   items: [
    //     'cli/installation',
    //     'cli/configuration',
    //     'cli/basic-usage',
    //     'cli/advanced-features',
    //     'cli/troubleshooting',
    //   ],
    // },
    {
      type: 'category',
      label: '📚 SpoonOS API Reference',
      collapsed: false,
      link: {
        type: 'doc',
        id: 'api-reference/index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'api-reference/spoon_ai',
        },
      ],
    },
    {
      type: 'category',
      label: '💡 Examples',
      collapsed: true,
      items: [
        'examples/intent-graph-demo',
        'examples/graph-crypto-analysis',
        'examples/mcp-spoon-search-agent',
        'examples/x402-react-agent',
      ],
    },
    {
      type: 'category',
      label: '🔧 Troubleshooting',
      collapsed: true,
      items: [
        'troubleshooting/common-issues',
        'troubleshooting/debugging',
        'troubleshooting/performance',
      ],
    },
  ],
};

export default sidebars;
